project:
  type: book

book:
  title: "Big Book of MLOps"
  author: "Jamie Ralph"
  date: "9/24/2024"
  chapters:
    - index.qmd
    - networking.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



